INCLUDE:
  - conf/dev/global/config.yaml

# 全局服务
service_list:
  - path: modules/service/http_module/simple_http/simple_http_comp.py  # HTTP服务
    conf: conf/dev/service/http/http.yaml
  - path: modules/service/http_module/simple_http/simple_http_comp.py  # 手机检测定制化HTTP服务
    conf: conf/dev/service/http/http_phone.yaml
#  - path: modules/service/insight_module/insight/zero/component/insight_comp.py  # 人脸识别服务
#    conf: conf/dev/service/face/insight/insight.yaml

# 视频流
stream_list:
  - path: modules/zero/core/component/stream_comp.py
    conf: conf/dev/stream/stream1.yaml

# 算法
algorithm_list:
  # ------------------- 目标检测算法 -------------------
#  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 计数
#    conf: conf/dev/detection/yolox/yolox_count.yaml
#  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 人头
#    conf: conf/dev/detection/yolox/yolox_head.yaml
  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 人
    conf: conf/dev/detection/yolox/yolox_person.yaml
#  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 安全帽
#    conf: conf/dev/detection/yolox/yolox_helmet.yaml
  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 手机
    conf: conf/dev/detection/yolox/yolox_phone.yaml
  # ------------------- 业务算法 -------------------
#  - path: modules/business/count/count_comp.py  # 计数（计数）
#    conf: conf/dev/business/count/count1.yaml
#  - path: modules/business/renlian/renlian_comp.py  # 人脸（人头）
#    conf: conf/dev/business/face/face1.yaml
#  - path: modules/business/intrude/intrude_comp.py  # 入侵（人+人脸）
#    conf: conf/dev/business/intrude/intrude1.yaml
#  - path: modules/business/helmet/helmet_comp.py  # 安全帽（人+安全帽）
#    conf: conf/dev/business/helmet/helmet1.yaml
#  - path: modules/business/card/card_comp.py  # 代刷卡（人）
#    conf: conf/dev/business/card/card1.yaml
  - path: modules/business/phone/phone_comp.py  # 手机（人+手机）
    conf: conf/dev/business/phone/phone1.yaml

app:
  running_file: bin/dev/runtime.pkl  # 框架运行时标识路径，运行时生成，删除该文件可以关闭算法端
  analysis_enable: True  # 是否打印性能分析报告
  analysis_interval: 5  # 每隔x秒打印一次性能分析报告

update_fps: 1  # 主进程更新帧率