INCLUDE:
  - conf/dev/global/log.yaml

# 全局服务
service_list: []
#  - path: modules/insight_module/insight/zero/component/insight_comp.py
#    conf: conf/dev/service/face/insight/insight.yaml

# 视频流
stream_list:
  - path: modules/zero_module/zero/core/component/stream_comp.py
    conf: conf/dev/stream/stream1.yaml

# 算法
algorithm_list:
  - path: modules/yolox_module/yolox/zero/component/yolox_comp.py
    conf: conf/dev/detection/yolox/yolox_person.yaml

app:
  running_file: bin/dev/runtime.pkl  # 框架运行时标识路径，运行时生成，删除该文件可以关闭算法端
  analysis_interval: 5  # 每隔x秒打印一次性能分析报告

# 主进程更新帧率
update_fps: 1
