INCLUDE:
  - conf/pro/global/config.yaml

# 全局服务
service_list:
  - path: modules/service/http_module/simple_http/simple_http_comp.py  # HTTP服务
    conf: conf/pro/service/http/http.yaml
  - path: modules/service/insight_module/insight/zero/component/insight_comp.py  # 人脸识别服务
    conf: conf/pro/service/face/insight/insight.yaml

# 视频流
stream_list:
  - path: modules/zero/core/component/stream_comp.py  # 111: 计数
    conf: conf/pro/stream/stream1.yaml
  - path: modules/zero/core/component/stream_comp.py  # 112: 计数
    conf: conf/pro/stream/stream2.yaml
#  - path: modules/zero/core/component/stream_comp.py # 113: 无用
#    conf: conf/pro/stream/stream3.yaml
  - path: modules/zero/core/component/stream_comp.py  # 114: 人脸
    conf: conf/pro/stream/stream4.yaml
#  - path: modules/zero/core/component/stream_comp.py # 115: 无用
#    conf: conf/pro/stream/stream5.yaml
  - path: modules/zero/core/component/stream_comp.py # 116: 人脸，安全帽
    conf: conf/pro/stream/stream6.yaml
  - path: modules/zero/core/component/stream_comp.py # 117: 入侵
    conf: conf/pro/stream/stream7.yaml
  - path: modules/zero/core/component/stream_comp.py # 118: 代刷卡
    conf: conf/pro/stream/stream8.yaml
  - path: modules/zero/core/component/stream_comp.py # 119: 手机
    conf: conf/pro/stream/stream9.yaml
  - path: modules/zero/core/component/stream_comp.py # 120: 手机
    conf: conf/pro/stream/stream10.yaml
# 算法
algorithm_list:
  # ------------------- 目标检测算法 -------------------
#  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 人头
#    conf: conf/pro/detection/yolox/yolox_head.yaml
  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 人1
    conf: conf/pro/detection/yolox/yolox_person1.yaml
  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 人2
    conf: conf/pro/detection/yolox/yolox_person2.yaml
  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 安全帽
    conf: conf/pro/detection/yolox/yolox_helmet.yaml
  - path: modules/algorithm/yolox_module/yolox/zero/component/yolox_comp.py  # 手机
    conf: conf/pro/detection/yolox/yolox_phone.yaml
  # ------------------- 业务算法 -------------------
  - path: modules/business/count/count_comp.py  # 计数1
    conf: conf/pro/business/count/count1.yaml
  - path: modules/business/count/count_comp.py  # 计数2
    conf: conf/pro/business/count/count2.yaml
  - path: modules/business/renlian/renlian_comp.py  # 人脸4
    conf: conf/pro/business/renlian/renlian4.yaml
  - path: modules/business/renlian/renlian_comp.py  # 人脸6
    conf: conf/pro/business/renlian/renlian6.yaml
  - path: modules/business/intrude/intrude_comp.py  # 入侵7
    conf: conf/pro/business/intrude/intrude7.yaml
  - path: modules/business/helmet/helmet_comp.py  # 安全帽6
    conf: conf/pro/business/helmet/helmet6.yaml
  - path: modules/business/card/card_comp.py  # 代刷卡8
    conf: conf/pro/business/card/card8.yaml
  - path: modules/business/phone/phone_comp.py  # 手机9
    conf: conf/pro/business/phone/phone9.yaml
  - path: modules/business/phone/phone_comp.py  # 手机10
    conf: conf/pro/business/phone/phone10.yaml

app:
  running_file: bin/pro/runtime.pkl  # 框架运行时标识路径，运行时生成，删除该文件可以关闭算法端
  analysis_enable: True  # 是否打印性能分析报告
  analysis_interval: 20  # 每隔x秒打印一次性能分析报告

update_fps: 1  # 主进程更新帧率